causalpy/data/datasets.py
docs/api_datasets.rst
docs/index.rst

Small update. Includes the `load_data` function in the API documentation via autodoc.

get dataset included in autodoc

---

docs/conf.py

Syntax highlighting in just the ipynb files stopped working, and just in the remote readthedocs build. Unclear why this happened.

HOTFIX: attempt to get syntax highlighting in remote readthedocs build working again

---

docs/conf.py
requirements.txt

Revert last change, add ipython to requirements.txt

HOTFIX: second attempt to fix syntax highlighting in ipynb files on remote rtd build

---

docs/conf.py
requirements.txt

Addresses #103. Let's see if it works!

Fix docs syntax highlighting issue? Temporary fix by disallowing ipython 8.7.0

---

.isort.cfg
causalpy/pymc_models.py
causalpy/tests/conftest.py
causalpy/tests/test_dummy.py
causalpy/tests/test_pymc_models.py

This PR adds some basic test for the model builder class. I also fixed the problem of having mutable structures as default, see for example https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil/
I also started adding more strict type hints as I strongly recommend to start using `mypy` for static type checking now as it s still a young project :)

Add tests Model Builder

---

causalpy/plot_utils.py

hey! this PR just correct some type hints: From the [documentation](https://mypy.readthedocs.io/en/stable/kinds_of_types.html#optional-types-and-the-none-type):
> You can use the [Optional](https://docs.python.org/3/library/typing.html#typing.Optional) type modifier to define a type variant that allows None, such as Optional[int] (Optional[X] is the preferred shorthand for Union[X, None])
This means that a parameter with a default value is not an `Optional` type. We will capture these type of errors once we set up `mypy`. 
In addition, we should not use mutable structures as defaults. It is better to set `None` as default, see https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil/

fix optional type hints

---

causalpy/tests/test_integration_skl_examples.py
pyproject.toml
pytest.ini

My attempt at starting #25. Here are some integration tests to cover just the sklearn based models. So far I've added a test for every example in the docs.
I've also given these a custom mark of `integration` and we can just run those tests alone with `pytest -v -m integration`.
All tests pass.
Let me know if you have suggested changes. After the approach for integration tests is sorted then I'll add equivalent tests for the pymc based examples.

add integration tests covering the sklearn examples from the docs

---

causalpy/pymc_experiments.py
causalpy/tests/test_integration_pymc_examples.py
docs/notebooks/did_pymc.ipynb
docs/notebooks/did_pymc_banks.ipynb

The group variable is dummy coded as 0/1, rather than categorical, so we don't need to have these kwargs any more.
Closes #150

remove `treated` and `untreated` kwargs for DifferenceInDifferences

---

.github/workflows/ci.yml

This PR makes CI run only on pushes or PRs that target the main branch.
The original behavior was to run the CI action upon the `push` event in any branch. When attempting a PR from a fork, that means that the CI actions would be run on the fork repo instead of the upstream repo. As a consequence, PRs from forks wouldn't show any CI action workflows, and would seem clean and ready for merging (e.g. #167 that has its action workflow [here](https://github.com/lucianopaz/CausalPy/actions/runs/4182434551))

Only run CI on pushes or PRs to the main branch

---

.github/workflows/ci.yml
.pre-commit-config.yaml

#166 and #163 ran into lint failures. I think that this was caused by using `make init` and `make lint`, which have unpinned versions of lint scripts. One way to avoid this and to have an encapsulated CI step is to rely on `pre-commit` itself to run the lint step.

Fix lint CI step

---

.github/workflows/ci.yml
README.md
codecov.yml

Add codecov

---

README.md
docs/index.rst

Adds PyData Global 2022 talk on CausalPy to the docs + README.
Closes #75.

add pydata global 2022 video to README and docs

---

pyproject.toml

There was a mistake in the previous version bump today for 0.0.10. The tag did not match up with what was in `pyproject.toml`. So hopefully this fixes things.

version bump to #0.0.11

---

MANIFEST.in
docs/source/_static/interrogate_badge.svg
pyproject.toml

Add the csv data files into the package data discovery

---

.pre-commit-config.yaml
docs/source/_static/interrogate_badge.svg
docs/source/conf.py
docs/source/glossary.md
docs/source/notebooks/ancova_pymc.ipynb
docs/source/notebooks/did_pymc.ipynb
docs/source/notebooks/did_pymc_banks.ipynb
docs/source/notebooks/geolift1.ipynb
docs/source/notebooks/its_covid.ipynb
docs/source/notebooks/its_pymc.ipynb
docs/source/notebooks/rd_pymc.ipynb
docs/source/notebooks/rd_pymc_drinking.ipynb
docs/source/notebooks/rd_skl_drinking.ipynb
docs/source/notebooks/sc_pymc.ipynb
docs/source/notebooks/sc_pymc_brexit.ipynb
docs/source/references.bib
pyproject.toml

* This PR enables you to use bibtex references in the documentation.
* Extension changes: This is done through `sphinxcontrib.bibtex`, but we also now use `myst_nb` (see https://myst-nb.readthedocs.io/en/latest/index.html) and no explicitly use `nbsphinx` or `myst_parser`. 
* That change to use `myst_nb` also allowed us to use simpler admonitions, so this was changed in all the relevant example notebooks.
* Default behaviour is to collect all references (site wide) into a single reference section. But because the site is / will be heavy with example notebooks then it makes sense to keep references at the end of each notebook. This is the same style as the `pymc-examples` repo.
* This will close #214.

Enable bibtex references in the documentation

---

causalpy/pymc_experiments.py
causalpy/skl_experiments.py
causalpy/tests/test_integration_pymc_examples.py
causalpy/tests/test_integration_skl_examples.py

Epsilon is the (small) distance above and below the threshold that we use to calculate the discontinuity. Previously this was hard-wired to be 0.001, but now we have a kwarg `epsilon` that can be used to override the default (still 0.001).
Added a short description in the docstring.
Added use of the kwarg into the integration tests.
Closes #220.

Add an `epsilon` parameter to `RegressionDiscontinuity` classes

---

causalpy/pymc_models.py
pyproject.toml

improve math rendering of pymc model docs

---

README.md

Simple update of website and email contact details following the switch from .io to .com domain.

update website and email contact details from .io to .com domain

---

causalpy/pymc_experiments.py

This resolves issue #161 
I tried the PrePostNEGD example with `group` being binary (current), boolean, or categorical with levels 'A' and 'B'. All three pass the `_series_has_2_levels` check but in the prediction after model fitting, errors result in the 'A'/'B' case because 'untreated' is given values of 0 (and 'treated' 1). Switching to `_is_variable_dummy_coded` moves the error to a data exception in the input validation, which makes more sense.
A more complicated fix would be to assign the two levels in lines 1059 and 1070 rather than 0's and 1's, but then we would need to know which is the 'treatment' level so probably best to leave those transformations to users.
I also fixed a bug that requires the group variable to be called 'group' and adjusted some re-used variable names whose …

fix PrePostNEGD input validation

---

causalpy/pymc_experiments.py
causalpy/tests/test_pymc_experiments.py
docs/source/_static/interrogate_badge.svg

Fix error in plot method

---

.pre-commit-config.yaml
README.md
causalpy/__init__.py
docs/source/notebooks/did_skl.ipynb
docs/source/notebooks/geolift1.ipynb
pyproject.toml
setup.cfg

Closes https://github.com/pymc-labs/CausalPy/issues/267

Adopt Ruff linter and formatter 

---

README.md

I replaced the image links in the `README.md` with their absolute paths. This should fix issue #261 .
The `codecov` link is unchanged and will still not be displayed properly on PyPi (probably because of the required token id).

add absolute paths to images in README to fix PiPy description

---

Makefile
causalpy/__init__.py
causalpy/pymc_experiments.py
causalpy/tests/test_input_validation.py
pyproject.toml

This PR replaces makefile commands with the ruff linter and formatted. The PR resolves #271 
Changes:  
- Add isort rules to ruff config in the `poetry.toml` file
- Replace existing noqa in the codebase with ruff noqa syntax
- Replace the makefile commands with 
Unfortunately, `nbqa` is only compatible with `ruff check`/`ruff` command  not the `ruff format` so I kept it as is!

Replace makefile commands with ruff 

---

.github/workflows/ci.yml
Makefile

Ignore `causalpy/tests/` when running doctest to save a little time. Resolves issue #278.
This cuts out the tests from being run twice, and doesn't doctest the docstrings in the tests - but none of them have examples so the doctests weren't doing much.
Locally, this went from 4m 50s to 3m 20s, so ~40% reduction in time.

Ignore `causalpy/tests/` when running doctest to save a little time

---

causalpy/pymc_experiments.py
causalpy/skl_experiments.py

changed splitting behaviour for PrePostFit

---

causalpy/pymc_experiments.py

Resolve issue #284 by reducing the data used for an example and removing the summary output from RegressionDiscontinuity which seemed particularly fickle.

simplify doctest outputs

---

causalpy/pymc_experiments.py
causalpy/pymc_models.py
causalpy/tests/test_pymc_models.py

Problems with doctests passing revealed that we were only passing the `random_seed` kwarg to the `pm.sample` method and that this was not being passed into `pm.sample_prior_predictive` or `pm.sample_posterior_predictive`. 
This will hopefully avoid any future issues in doctest fragility. But it is also a pretty useful (if not essential) fix to make.
Closes #284.

Make results fully reproducible 

---

causalpy/pymc_experiments.py
causalpy/skl_experiments.py

* Closes #282 
* Doctests and tests pass locally.
* Docstrings updated to reflect the new output you get.

User specified number of significant figures for numerical outputs

---

causalpy/pymc_models.py

Closes issue #288.
Removes the `FutureWarning` in tests caused by a deprecated property:
```
FutureWarning: Model.model property is deprecated. Just use Model.
warnings.warn("Model.model property is deprecated. Just use Model.", FutureWarning)
```

Fix #288: remove deprecated 'model' property in tests.

---

causalpy/pymc_experiments.py

Fix #300: Set `round_to` as an optional argument.

---

.github/workflows/ci.yml
.github/workflows/release.yml

`Node.js 16` actions are deprecated. The warning message suggests updating the following actions to `Node.js 20`: 
- actions/checkout@v3
- actions/setup-python@v4 
- actions/upload-artifact@v3
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
To see the warning check any action in the Actions tab.

Upload versions due to Node 16 sunset.

---

CONTRIBUTING.md
Makefile

Closes #287.
To test it, I created a new virtual environment (with `pyenv`) from scratch and ran the installation commands and the `Makefile` commands as well.
This PR seems to overlap a bit with [this one](https://github.com/pymc-labs/CausalPy/pull/304).

Fix #287 Update Makefile

---

.github/workflows/ci.yml
.github/workflows/release.yml
CONTRIBUTING.md
pyproject.toml

After the arviz release, the test kept failing because arviz 0.18.0 does not support Python 3.9 (https://github.com/arviz-devs/arviz/pull/2315/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7).
This PR drops support for 3.8 and 3.9 and adds support for 3.11.

Drop support for Python 3.8 and 3.9, add 3.11

---

docs/source/design_notation.md
docs/source/glossary.rst
docs/source/index.rst
docs/source/references.bib

* In this discussion https://github.com/pymc-labs/CausalPy/discussions/262 I floated the idea of adding some didactic information to the docs. This PR represents my first attempt to do that.
* It adds a new section on the left navbar, called `Knowledge Base`
* And it adds a new page which runs through the tabular **experiment design notation** established in Shadish Cook & Campbell (2002) and Reichardt (2009).
* Happy to have some feedback

Add experiment design notation docs page to new Knowledge Base section of the docs

---

.github/workflows/ci.yml
.github/workflows/release.yml

This PR reverts the changes in #310. Should fix the issues with the release.
The upgrade of the Artifacts actions to v4 requires a deeper look: https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

Revert the GitHub Actions update due to Node 16 sunset.

---

.github/workflows/ci.yml
.github/workflows/release.yml
.pre-commit-config.yaml
causalpy/data/__init__.py
causalpy/data/datasets.py
causalpy/data/simulate_data.py
causalpy/skl_experiments.py
causalpy/skl_models.py
causalpy/tests/conftest.py
causalpy/tests/test_data_loading.py
causalpy/utils.py

This PR adds the feature to use https://pre-commit.ci/ to generate automatic version updates of the pre-commit versions. This is already working on pymc-marketing: https://github.com/pymc-labs/pymc-marketing/blob/main/.pre-commit-config.yaml  Note I deleted the GitHub action as it will be a duplicate after this one is merged (https://github.com/pymc-devs/pymc/pull/7285)
@drbenvincent Can you please log into https://pre-commit.ci/ and grant access to this repository after we merge this PR? We then can start getting these automatic PRs as in https://github.com/pymc-labs/pymc-marketing/pull/655
I ran `pre-commit run --all-files` to verify everything was working as expected. The result is that some files were modified just by adding a white space.

Automate pre commit updates

---

causalpy/pymc_models.py
causalpy/tests/test_pymc_models.py
pyproject.toml

* Closes #324
* Was previously `pymc>=5.0.0` but now `pymc>=5.14.0`
* Note: we have a separate issue which is causing some doctests to pass (see #323), that is not introduced by this PR

Fix `FutureError` warning, which requires `pymc>=5.14.0`

---

.pre-commit-config.yaml
causalpy/__init__.py
causalpy/custom_exceptions.py
causalpy/data/__init__.py
causalpy/data/datasets.py
causalpy/data/simulate_data.py
causalpy/data_validation.py
causalpy/plot_utils.py
causalpy/pymc_experiments.py
causalpy/pymc_models.py
causalpy/skl_experiments.py
causalpy/skl_models.py
causalpy/tests/__init__.py
causalpy/tests/conftest.py
causalpy/tests/test_data_loading.py
causalpy/tests/test_input_validation.py
causalpy/tests/test_integration_pymc_examples.py
causalpy/tests/test_integration_skl_examples.py
causalpy/tests/test_pymc_experiments.py
causalpy/tests/test_pymc_models.py
causalpy/tests/test_utils.py
causalpy/utils.py
causalpy/version.py

Bringing this from PyMC-Marketing. 
See the issue: https://github.com/pymc-labs/pymc-marketing/issues/672 and the PR: https://github.com/pymc-labs/pymc-marketing/pull/673
~~I can create an additional PR like https://github.com/pymc-labs/pymc-marketing/pull/674 to ignore this commit from `git blame`.~~

Add license

---

causalpy/pymc_experiments.py
causalpy/pymc_models.py

* Closes #323 which is affecting current PR's.
* Also managed to catch a bug where we were not passing in `random_seed` to `pm.sample_posterior_predictive` in `ModelBuilder.predict`. Also replaced a multi-line block with the single line `random_seed = self.sample_kwargs.get("random_seed", None)` which is much nicer.
* Other than that, the solution was to add varying numbers of `<BLANKLINE>` to the docstrings. I believe this is because the pymc progress bar is returning empty lines, possibly only in the instance where `progressbar=False`. I should open an issue in the PyMC repo about that.
* All tests and doctests pass in my local environment, which was build in the conda-based approach, see #304. Remains to be seen if the doctests will pass remotely.

Fix failing doctests

---

pyproject.toml

See https://github.com/pymc-labs/CausalPy/issues/327#issuecomment-2096256657

Bound MyST NB to fix the compressed images.

---

causalpy/pymc_experiments.py
causalpy/pymc_models.py
causalpy/skl_experiments.py
environment.yml

* Removes a bunch of `<BLANKLINE>` instances in the docstrings. They were put there in #330 in order to fix failing tests. And that was happening because the progress bar was misbehaving.
* This was fixed in https://github.com/pymc-devs/pymc/pull/7290 so we no longer need most `<BLANKLINE>` instances.
* This PR removes those, **and increments the required version of PyMC to `5.15.1`** which is the version to include https://github.com/pymc-devs/pymc/pull/7290
* Closes #331 
* This should also fix failing remote tests that we are seeing in other PR's.

Remove `<BLANKLINE>` from docstrings

---

.github/workflows/ci.yml
.github/workflows/release.yml
pyproject.toml

* Adds support for Python 3.12 in that it runs the remote tests with 3.12 now
* Closes #318

Add support for Python 3.12

---

.github/workflows/ci.yml

Suggestion by @maresb. Should speed up remote actions, slightly.

Simplify remote GitHub actions by building test environment only once

---

Makefile
pyproject.toml

* In #352 I forgot to nuke all mention of nbqa from the repo
* This PR does that, removing it from `pyproject.toml` and the `Makefile`

Remove all remaining traces of `nbqa` from the repo

---

.github/workflows/rtd-link-preview.yml
.gitignore
.readthedocs.yaml
README.md
docs/source/conf.py
docs/source/index.rst
pyproject.toml

Multiple changes related to documentation infrastructure.
Can add some more depending on preferences.
* Add conda forge install instructions
* add viewcode and copybutton extensions. They add the [source] link to docs and a copybutton to
copy whole cells. I will double check, but using the copy button should also copy the snippets
in docstrings like the one in https://causalpy.readthedocs.io/en/latest/api_skl_experiments.html
without the >>> parts.
* Add the rtd-preview workflow that adds a link to the PR documentation preview as text at the
bottom of the PR description. From what I see, PR doc preview aren't active yet, this can
be done from https://readthedocs.org/dashboard/causalpy/edit/, scroll down and check
the
> Build pull requests for this project:
> * [ ] More information in our …

Various improvements to documentation infrastructure

---

docs/source/conf.py
pyproject.toml

closes #373
----
📚 Documentation preview 📚: https://causalpy--376.org.readthedocs.build/en/376/

fix docstring example rendering

---

docs/source/knowledgebase/causal_video_resources.md
docs/source/knowledgebase/index.md

1. Added the `causal_video_resources` page markdown file for the PyMC Labs Videos, used iframe to add the videos.
2. Tested if the UI is responsive or not in both light and dark mode.
3. Updated the `index.md` for the knowledge base to include the page link for the `causal_video_resources`.
https://github.com/pymc-labs/CausalPy/assets/76129377/7305cb30-6a73-4c7c-a403-8c2e916219d6
----
📚 Documentation preview 📚: https://causalpy--379.org.readthedocs.build/en/379/

Add page of causal video resources from PyMC community into the docs

---

causalpy/pymc_models.py

Closes #410 
----
📚 Documentation preview 📚: https://causalpy--414.org.readthedocs.build/en/414/

Fix SyntaxWarning by making some docstrings raw

---

causalpy/pymc_models.py

* Previously, the `r2_score` was calculated by comparing `y_true` and `y_pred`, where `y_pred` was the likelihood-influenced predictions i.e. with the observation noise added. Now we set `y_pred` to be based on the model's expected outcomes.
* Closes #428
----
📚 Documentation preview 📚: https://causalpy--429.org.readthedocs.build/en/429/

Calculate goodness of fit (`r2_score`) based on posterior expectation rather than posterior prediction

---

causalpy/data/simulate_data.py
causalpy/experiments/diff_in_diff.py
causalpy/experiments/instrumental_variable.py
causalpy/experiments/inverse_propensity_weighting.py
causalpy/experiments/prepostfit.py
causalpy/experiments/prepostnegd.py
causalpy/pymc_models.py
pyproject.toml

* Updates `pyproject.toml` to get ruff to format docstrings. Triggered in pre-commit checks.
* Ran that, so we've got formatting updates to a bunch of docstrings.
----
📚 Documentation preview 📚: https://causalpy--430.org.readthedocs.build/en/430/

Enable ruff formatting of docstrings

---

.github/workflows/uml.yml
Makefile
pyproject.toml

* updates pyproject.toml to include `pylint` (which contains `pyreverse`) in the optional docs dependencies
* updates the makefile to load the docs optional dependencies
----
📚 Documentation preview 📚: https://causalpy--446.org.readthedocs.build/en/446/

fixes for uml github action

---

causalpy/pymc_models.py

This PR contains a quick bug fix for issue: #452 :
- Replaced `MutableData` with `Data` in the `PropensityScore` class
----
📚 Documentation preview 📚: https://causalpy--455.org.readthedocs.build/en/455/

Replaced `MutableData` with `Data`

---

causalpy/experiments/diff_in_diff.py
causalpy/experiments/interrupted_time_series.py
causalpy/experiments/prepostnegd.py
causalpy/experiments/regression_discontinuity.py
causalpy/experiments/regression_kink.py
causalpy/experiments/synthetic_control.py
causalpy/pymc_models.py

* Closes #459
* global find and replace obs_indx -> obs_ind
* Also had to update `PyMCModel._data_setter` to make it work
* All tests + doctests work locally, so the remote tests should also work 🤞🏻
----
📚 Documentation preview 📚: https://causalpy--462.org.readthedocs.build/en/462/

fix bug: obs_indx -> obs_ind and improve `PyMCModel._data_setter`

---

README.md

* The build badge now reflects the status of `main`. Previously if the latest ci build failed (even if it was from developmental work in a feature branch), the badge would show as failed. That gave a misleading picture of the repo status.
* I also updated the Ruff badge. Previous it was red, and red is angry and bad.
----
📚 Documentation preview 📚: https://causalpy--465.org.readthedocs.build/en/465/

Update badges on GitHub landing page

---

docs/source/index.md

This small PR fixes the PyMC site reference found at https://causalpy.readthedocs.io/en/stable/.
----
📚 Documentation preview 📚: https://causalpy--466.org.readthedocs.build/en/466/

Fix PyMC site reference

---

README.md
docs/source/knowledgebase/causal_written_resources.md
docs/source/knowledgebase/index.md

#71 Outline for general markdown for causal inference written resources with update to index.md. Separating the awesome causal inference section by Matt Courthoud and essential written resources for the CausalPy package. 
----
📚 Documentation preview 📚: https://causalpy--447.org.readthedocs.build/en/447/

Add new list of written learning resources to the docs

---

.github/workflows/label-precommit-prs.yml

Resolves the issue where auto-generated pre-commit update PRs were missing the "no releasenotes" label.
This workflow "label-precommit-prs.yml" file checks if a PR title includes "pre-commit autoupdate" and automatically applies the "no releasenotes" label. This ensures consistent labeling of automated PRs and improves release note handling.
Closes #[69]
----
📚 Documentation preview 📚: https://causalpy--471.org.readthedocs.build/en/471/

Auto-label pre-commit autoupdate PRs with "no releasenotes"

---

codecov.yml
pyproject.toml

Closes #490 from @williambdean 
I vibe coded this, so could do with a close inspection.
----
📚 Documentation preview 📚: https://causalpy--493.org.readthedocs.build/en/493/

Exclude causalpy/tests from code coverage

---

.github/workflows/ci.yml
Makefile
causalpy/experiments/prepostnegd.py
causalpy/tests/conftest.py
causalpy/tests/test_integration_pymc_examples.py
causalpy/tests/test_pymc_models.py
pyproject.toml

Saving about 50s in the test suite by mocking `pm.sample`
----
📚 Documentation preview 📚: https://causalpy--489.org.readthedocs.build/en/489/

Use mock sample in tests

---

causalpy/data/simulate_data.py

Closes #433
> P.S.: In the same function, should the input intercept (i.e. `beta_intercept`) in the output dataframe instead of the constant `1`
I believe the answer to this is "no". The `beta_intercept` input is being used in the data generation process, but the purpose of `df["intercept"] = np.ones(df.shape[0])` is to create input data for modelling where it's common to create a column of zeros. Though practically I think this is not needed or is even being used because it's being taken care of by `patsy` based on the user-provided model formula. But for the moment I've just added an explanatory comment.
----
📚 Documentation preview 📚: https://causalpy--505.org.readthedocs.build/en/505/

Fix to minor bug in simulated data generation function

---

docs/source/index.md

The [landing page](https://causalpy.readthedocs.io/en/latest/) for CausalPy
has spaces in the code blocks. These should be removed for better formatting.
----
📚 Documentation preview 📚: https://causalpy--527.org.readthedocs.build/en/527/

Remove spaces from docs landing page
